apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/flagger
  - ../base/nginx-ingress
patchesStrategicMerge:
  - flagger.yaml
  - nginx-ingress-helmrelease.yaml

namespace: flagger-system
